export const API_ENDPOINT = 'https://5a699de4d039b9001222448e.mockapi.io/api/flights'
export const FETCH_FLIGHTS_REQUEST = 'FETCH_FLIGHTS_REQUEST'
export const FETCH_FLIGHTS_SUCCESS = 'FETCH_FLIGHTS_SUCCESS'
export const FETCH_FLIGHTS_FAILURE = 'FETCH_FLIGHTS_FAILURE'